-- Annotation cost probes — read-only measurement, run by the maintainer.
--
-- These decide two pending changes that must NOT be built on guesswork:
--
--   Probe A  -> should the bot stop annotating the translation side of every message?
--               (halves annotation spend, but halves flashcard supply if traffic is
--                lopsided)
--   Probe B  -> is a surface-form -> lemma cache worth building?
--               (eliminates repeat API calls entirely, but only if the hit rate is real)
--   Probe C  -> how much of that cache would be disqualified by word-sense ambiguity.
--
-- Every query returns COUNTS ONLY. No message text is selected by any of them. Probe A
-- reads users.display_name so the result is legible; that is the only non-aggregate
-- column anywhere in this file.
--
-- Safe to run against the live database: all statements are plain SELECTs, nothing is
-- created, written or dropped. Run each block separately and keep the output.


-- ============================================================================
-- Probe A1 — who writes in which language?
-- ============================================================================
-- Reads as: "<name> (native X, learning Y) wrote N messages in Z."
--
-- What to look for: whether each partner writes mostly in their NATIVE language. The
-- translation pass only matters much if someone routinely writes in the language they
-- are learning, because then their partner's cards come from the machine side.

select
  u.display_name,
  u.native_language,
  u.learning_language,
  m.original_language as wrote_in,
  count(*)            as messages,
  round(100.0 * count(*) / sum(count(*)) over (partition by u.id), 1) as pct_of_their_messages
from public.messages m
join public.users u on u.id = m.sender_id
where m.created_at >= now() - interval '90 days'
group by u.id, u.display_name, u.native_language, u.learning_language, m.original_language
order by u.display_name, messages desc;


-- ============================================================================
-- Probe A2 — THE DECISION QUERY for dropping the translation pass
-- ============================================================================
-- For each language, how many annotatable sides were written by a human (the original)
-- versus generated by the bot (the translation).
--
-- `pct_retained` is exactly what survives if the translation pass is dropped: the share
-- of that language's future flashcard supply that comes from human-written text.
--
-- Rule of thumb: 40-60% retained in BOTH languages means the cut is safe and each
-- partner keeps a healthy deck sourced from authentic writing. If either language drops
-- below ~25%, that learner is being fed almost entirely by machine text today and the
-- cut would starve them — abandon the change.

select
  lang,
  count(*) filter (where side = 'original')    as human_written,
  count(*) filter (where side = 'translation') as machine_written,
  count(*)                                     as total_sides,
  round(100.0 * count(*) filter (where side = 'original') / nullif(count(*), 0), 1)
    as pct_retained
from (
  select original_language as lang, 'original' as side
  from public.messages
  where created_at >= now() - interval '90 days'
    and original_text is not null
  union all
  select translated_language as lang, 'translation' as side
  from public.messages
  where created_at >= now() - interval '90 days'
    and translated_text is not null
) s
where lang is not null
group by lang
order by lang;


-- ============================================================================
-- Probe B — lemma-cache hit rate
-- ============================================================================
-- Simulates the proposed cache against real history. A side is a "hit" if every word in
-- it (>=3 letters, matching the app's ANNOTATABLE_WORD regex) had already appeared in an
-- EARLIER message in the same language — meaning the cache could have served it for free
-- and no API call was needed.
--
-- The token vocabulary is built from ALL history, but the hit rate is reported only over
-- the trailing 30 days. That is deliberate: a whole-corpus figure is dragged down by the
-- cold-start period when nothing was cached yet, and badly understates steady state.
--
-- THIS IS AN UPPER BOUND. It assumes every token has a usable cached lemma and ignores
-- the sense-ambiguity exclusion measured in Probe C. Discount it accordingly — a reported
-- 60% is realistically more like 45%.
--
-- Worth building if the discounted rate clears ~35%. Below ~20%, the table and its
-- polysemy guard are not worth the moving parts.

with sides as (
  select id, created_at, original_language   as lang, original_text   as text
  from public.messages
  where original_text is not null and original_language is not null
  union all
  select id, created_at, translated_language as lang, translated_text as text
  from public.messages
  where translated_text is not null and translated_language is not null
),
toks as (
  select s.id, s.created_at, s.lang, lower(t.tok) as tok
  from sides s,
       lateral regexp_split_to_table(s.text, '[^[:alpha:]]+') as t(tok)
  where char_length(t.tok) >= 3
),
first_seen as (
  select lang, tok, min(created_at) as first_at
  from toks
  group by lang, tok
),
side_state as (
  select t.id, t.lang, t.created_at,
         bool_or(f.first_at >= t.created_at) as has_new_token
  from toks t
  join first_seen f on f.lang = t.lang and f.tok = t.tok
  group by t.id, t.lang, t.created_at
)
select
  lang,
  count(*)                                       as sides_last_30d,
  count(*) filter (where not has_new_token)      as would_hit_cache,
  round(100.0 * count(*) filter (where not has_new_token) / nullif(count(*), 0), 1)
    as pct_hit_upper_bound
from side_state
where created_at >= now() - interval '30 days'
group by lang
order by lang;


-- ============================================================================
-- Probe C — how ambiguous is the vocabulary already collected?
-- ============================================================================
-- The cache must never serve a word whose translation depends on context — that is the
-- "hard" -> важкий vs твердий failure the sense anchor exists to prevent. Any word seen
-- with more than one translation gets permanently disqualified from the cache.
--
-- `pct_ambiguous` is roughly how much of Probe B's upper bound that guard eats. Measured
-- at the lemma level (what the corpus records) rather than the surface level (what the
-- cache would key on), so treat it as indicative, not exact.

with per_lemma as (
  select
    details ->> 'language'                                    as lang,
    lower(annotation_value)                                   as lemma,
    count(distinct lower(details ->> 'lemma_translation'))     as senses
  from public.message_annotations
  where annotation_type = 'vocabulary'
    and details ->> 'lemma_translation' is not null
  group by 1, 2
)
select
  lang,
  count(*)                                   as distinct_lemmas,
  count(*) filter (where senses > 1)         as ambiguous_lemmas,
  round(100.0 * count(*) filter (where senses > 1) / nullif(count(*), 0), 1)
    as pct_ambiguous
from per_lemma
where lang is not null
group by lang
order by lang;
